#!/usr/bin/python
# Copyright (c) Members of the EGEE Collaboration. 2004. 
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.  
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#     http://www.apache.org/licenses/LICENSE-2.0 
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.

import sys
import re
import time
import shlex
import subprocess
from threading import Thread

from TorqueInfoUtils import CommonUtils
from TorqueInfoUtils import QStatHandler
from TorqueInfoUtils import PBSNodesHandler


def main():
    
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    try:
        if len(sys.argv) <> 2:
            raise Exception("Usage: info-dynamic-pbs <config-file>")
            
        config = CommonUtils.readConfigFile(sys.argv[1])

        if not "outputformat" in config:
            if "GlueFormat" in config:
                config["outputformat"] = config["GlueFormat"]
            else:
                config["outputformat"] = "both"
        if config["outputformat"] not in ["glue1", "glue2", "both"]:
            raise Exception("FATAL: Unknown output format specified in config file:%s" % config["outputformat"])

        if not "glue1-static-file-CE" in config:
            config["glue1-static-file-CE"] = "/var/lib/bdii/gip/ldif/static-file-CE.ldif"
        
        if not "glue2-static-file-computing-manager" in config:
            config["glue2-static-file-computing-manager"] = "/var/lib/bdii/gip/ldif/ComputingManager.ldif"
        
        if not "glue2-static-file-computing-share" in config:
            config["glue2-static-file-computing-share"] = "/var/lib/bdii/gip/ldif/ComputingShare.ldif"
            
        if not "pbs-host" in config:
            config["pbs-host"] = None

    except Exception, ex:
        sys.stderr.write(str(ex) + '\n')
        sys.exit(1)


    glue1QueueTable = dict()
    glue2QueueTable = dict()
    managerTable = None
    allQueues = set()
    qInfoHandlers = dict()
    
    try:
    
        if config['outputformat'] <> "glue2":
        
            glue1QueueTable = CommonUtils.parseGLUE1Queues(config["glue1-static-file-CE"])

            for queue in glue1QueueTable.values():
                allQueues.add(queue)

        if config['outputformat'] <> "glue1":

            glue2QueueTable = CommonUtils.parseGLUE2Shares(config["glue2-static-file-computing-share"])
            managerTable = CommonUtils.parseGLUE2Managers(config["glue2-static-file-computing-manager"])
            
            for queue in glue2QueueTable.values():
                allQueues.add(queue)

    
        lrmsVer = QStatHandler.parseLRMSVersion(config["pbs-host"])
        
        cpuInfoHandler = PBSNodesHandler.parseCPUInfo(config["pbs-host"])
    
        for queue in allQueues:
            qInfoHandlers[queue] = QStatHandler.parseQueueInfo(queue, config["pbs-host"])
            
    except Exception, ex:
        sys.stderr.write(str(ex) + '\n')
        sys.exit(2)

    out = sys.stdout
    
    if config['outputformat'] <> "glue2":

        for glue1DN in glue1QueueTable:
        
            queue = glue1QueueTable[glue1DN]
            qInfo = qInfoHandlers[queue]
            
            out.write(glue1DN + '\n')
            out.write('GlueCEInfoLRMSVersion: %s\n' % lrmsVer)
            
            out.write('GlueCEInfoTotalCPUs: %d\n' % cpuInfoHandler.totalCPU)
            out.write('GlueCEPolicyAssignedJobSlots: %d\n' % cpuInfoHandler.totalCPU)
            out.write('GlueCEStateFreeCPUs: %d\n' % cpuInfoHandler.freeCPU)
            
            if qInfo.maxCPUtime <> -1:
                out.write('GlueCEPolicyMaxCPUTime: %d\n' % (qInfo.maxCPUtime / 60))
                out.write('GlueCEPolicyMaxObtainableCPUTime: %d\n' % (qInfo.maxCPUtime / 60))
                
            if qInfo.maxTotJobs <> -1:
                out.write('GlueCEPolicyMaxTotalJobs: %d\n' % qInfo.maxTotJobs)
                
            if qInfo.policyPriority:
                out.write('GlueCEPolicyPriority: %s\n' % qInfo.policyPriority)
                
            if qInfo.maxRunJobs <> -1:
                out.write('GlueCEPolicyMaxRunningJobs: %d\n' % qInfo.maxRunJobs)
                
            if qInfo.maxTotJobs <> -1 and qInfo.maxRunJobs <> -1:
                out.write('GlueCEPolicyMaxWaitingJobs: %d\n' % (qInfo.maxTotJobs - qInfo.maxRunJobs))
                
            if qInfo.maxWallTime <> -1:
                out.write('GlueCEPolicyMaxWallClockTime: %d\n' % (qInfo.maxWallTime / 60))
                
            if qInfo.obtWallTime <> -1:
                out.write('GlueCEPolicyMaxObtainableWallClockTime: %d\n' % (qInfo.obtWallTime / 60))
                
            if qInfo.maxProcCount <> -1:
                out.write('GlueCEPolicyMaxSlotsPerJob: %d\n' % qInfo.maxProcCount)
 
            out.write('GlueCEStateStatus: %s\n' % qInfo.state)
            out.write('\n')


    if config['outputformat'] <> "glue1":

        for managerDN in managerTable:
        
            out.write(managerDN + '\n')
            out.write('GLUE2ManagerProductVersion: %s\n' % lrmsVer)
            out.write('GLUE2EntityCreationTime: %s\n' % now)
            out.write('\n')
            
        for glue2DN in glue2QueueTable:
            queue = glue2QueueTable[glue2DN]
            qInfo = qInfoHandlers[queue]
            
            out.write(glue2DN + '\n')
            if qInfo.maxCPUtime <> -1:
                out.write('GLUE2ComputingShareDefaultCPUTime: %d\n' % qInfo.maxCPUtime)
                out.write('GLUE2ComputingShareMaxCPUTime: %d\n' % qInfo.maxCPUtime)
            if qInfo.maxWallTime <> -1:
                out.write('GLUE2ComputingShareDefaultWallTime: %d\n' % qInfo.maxWallTime)
            if qInfo.obtWallTime <> -1:
                out.write('GLUE2ComputingShareMaxWallTime: %d\n' % qInfo.obtWallTime)
            if qInfo.maxProcCount <> -1:
                out.write('GLUE2ComputingShareMaxSlotsPerJob: %d\n' % qInfo.maxProcCount)
            if qInfo.maxRunJobs <> -1:
                out.write('GLUE2ComputingShareMaxRunningJobs: %d\n' % qInfo.maxRunJobs)
            if qInfo.maxTotJobs <> -1:
                out.write('GLUE2ComputingShareMaxTotalJobs: %d\n' % qInfo.maxTotJobs)
            if qInfo.maxTotJobs <> -1 and qInfo.maxRunJobs <> -1:
                out.write('GLUE2ComputingShareMaxWaitingJobs: %d\n' % (qInfo.maxTotJobs - qInfo.maxRunJobs))
            if qInfo.maxMem <> -1:
                out.write('GLUE2ComputingShareMaxMainMemory: %d\n' % qInfo.maxMem)
            if qInfo.maxVMem <> -1:
                out.write('GLUE2ComputingShareMaxVirtualMemory: %d\n' % qInfo.maxVMem)
                
            out.write('GLUE2ComputingShareServingState: %s\n' % qInfo.state.lower())
            out.write('GLUE2EntityCreationTime: %s\n' % now)
            out.write('\n')



if __name__ == "__main__":
    main()


